name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  run_small_dropbox:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
